[package]
name = "rust-israel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
